services:
  odyssai-backend:
    build: .
    container_name: odyssai-backend
    environment:
      - BACKEND_PORT=9000
    expose:
      - "9000"

  nginx:
    image: nginx:alpine
    container_name: odyssai-nginx
    ports:
      - "80:80"
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - odyssai-backend
