app = 'odyssai-core'
primary_region = 'cdg'

[build]

[http_service]
  internal_port = 9000
  force_https = false
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [http_service.concurrency]
    type = "requests"
    hard_limit = 25
    soft_limit = 20

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[[services]]
  internal_port = 9000
  protocol = "tcp"
  processes = ["app"]
  [[services.ports]]
    port = 80
  [[services.ports]]
    port = 443

[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/api/health"