# fly.toml app configuration file generated for odyssai-core on 2025-08-15T10:56:47+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'odyssai-core'
primary_region = 'cdg'

[build]

[http_service]
  internal_port = 9000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [http_service.concurrency]
    type = "requests"
    hard_limit = 25
    soft_limit = 20

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[[services]]
  internal_port = 9000
  protocol = "tcp"
  processes = ["app"]
  [[services.ports]]
    port = 80
  [[services.ports]]
    port = 443