app = 'odyssai-core'
primary_region = 'cdg'

[build]

[http_service]
  internal_port = 9000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [http_service.concurrency]
    type = "requests"
    hard_limit = 25
    soft_limit = 20

[[vm]]
  memory = "4096mb"
  cpu_kind = "shared"
  cpus = 2
  swap_size_mb = 1024

[[http_service.checks]]
  grace_period = "90s"
  interval = "15s"
  timeout   = "10s"
  method    = "GET"
  path      = "/"

[mounts]
  source = "hf_cache"
  destination = "/data/hf"

[env]
  HF_HOME = "/data/hf/.cache/huggingface"
  TRANSFORMERS_CACHE = "/data/hf/.cache/huggingface"