# name: Deploy to Production

# on:
#   workflow_run:
#     workflows: ["Build and Deploy Docker Image"]
#     branches: [main]
#     types:
#       - completed

# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     if: ${{ github.event.workflow_run.conclusion == 'success' }}

#     steps:
#       - name: Download deployment artifacts
#         uses: actions/download-artifact@v4
#         with:
#           name: deployment-config
#           github-token: ${{ secrets.GITHUB_TOKEN }}
#           run-id: ${{ github.event.workflow_run.id }}

#       # Déploiement automatique (nécessite configuration des secrets)
#       - name: Deploy to server via SSH
#         if: ${{ secrets.DEPLOY_HOST != '' }}
#         uses: appleboy/ssh-action@v1.0.3
#         with:
#           host: ${{ secrets.DEPLOY_HOST }}
#           username: ${{ secrets.DEPLOY_USER }}
#           key: ${{ secrets.DEPLOY_KEY }}
#           script: |
#             cd /opt/odyssai
#             # Login au registry GitHub
#             echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
#             # Pull et redéploiement
#             docker compose -f docker-compose.prod.yml pull
#             docker compose -f docker-compose.prod.yml up -d --remove-orphans
#             docker image prune -f
#             echo "✅ Déploiement terminé !"

#       # Notification si pas de serveur configuré
#       - name: Manual deployment notice
#         if: ${{ secrets.DEPLOY_HOST == '' }}
#         run: |
#           echo "🚀 Image buildée et disponible sur ghcr.io"
#           echo "📋 Pour déployer manuellement:"
#           echo "   docker pull ghcr.io/${{ github.repository }}:latest"
#           echo "   ./deploy.sh"
