name: Deploy to Fly.io

on:
  workflow_run:
    workflows: ["Build and Push Docker Image"]
    branches: [main]
    types:
      - completed

jobs:
  deploy:
    name: Deploy app remotely
    runs-on: ubuntu-24.04
    concurrency: deploy-group
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }} #
